-- ============================================================
-- 亚马逊财务系统 —— Supabase 云端建表 SQL
-- 用途：在能访问 Supabase 控制台时，打开 SQL Editor 执行本文件，
--       为「报表全面解读」新增的 4 张报表表建表。
--
-- 说明：现有 10 张表（transactions / profit_reports / import_logs /
--       accounts / roles / stores / saved_views / operation_logs /
--       exchange_rate / translations）已在迁移时创建，无需重复执行。
--       本文件只创建新增的 4 张表，重复执行不会报错（幂等）。
-- ============================================================

-- ============================================================
-- 1. 英文结算报表 settlements
--    数据来源：卖家中心 → 付款 → 结算报告（Settlement Report V2 flat file）
-- ============================================================
create table if not exists public.settlements (
  id bigint generated by default as identity primary key,
  settlement_id text,
  start_date text,
  end_date text,
  deposit_date text,
  total_amount numeric,
  currency text,
  transaction_type text,
  order_id text,
  order_item_id text,
  adjustment_id text,
  shipment_id text,
  marketplace_name text,
  fulfillment_id text,
  custom_text text,
  shipment_fee_type text,
  shipment_fee_amount numeric,
  order_fee_type text,
  order_fee_amount numeric,
  item_fee_type text,
  item_fee_amount numeric,
  other_fee_type text,
  other_fee_amount numeric,
  shipping_price numeric,
  item_price numeric,
  item_tax numeric,
  shipping_tax numeric,
  gift_wrap_price numeric,
  gift_wrap_tax numeric,
  item_promotion_discount numeric,
  shipment_promotion_discount numeric,
  promotional_rebate numeric,
  sales_tax_collected numeric,
  seller_promotion_id text,
  discount_amount numeric,
  cod_collection_fee numeric,
  sku text,
  quantity integer,
  price_type text,
  price_amount numeric,
  posted_date text,
  paid_date text,
  store_id text,
  month text,
  dedup_key text,
  created_at timestamptz default now(),
  constraint settlements_dedup_key_unique unique (dedup_key)
);
create index if not exists idx_settlements_month on public.settlements (month);
create index if not exists idx_settlements_sku on public.settlements (sku);

-- ============================================================
-- 2. 业务报告 business_reports
--    数据来源：卖家中心 → 数据报告 → 业务报告（Sales & Traffic，CSV）
-- ============================================================
create table if not exists public.business_reports (
  id bigint generated by default as identity primary key,
  date text,
  asin text,
  sku text,
  title text,
  sessions integer,
  session_percentage numeric,
  page_views integer,
  page_views_percentage numeric,
  buy_box_percentage numeric,
  units_ordered integer,
  unit_session_percentage numeric,
  ordered_product_sales numeric,
  total_order_items integer,
  conversion_rate numeric,
  store_id text,
  month text,
  dedup_key text,
  created_at timestamptz default now(),
  constraint business_reports_dedup_key_unique unique (dedup_key)
);
create index if not exists idx_business_reports_date on public.business_reports (date);
create index if not exists idx_business_reports_asin on public.business_reports (asin);

-- ============================================================
-- 3. 广告报告 ad_reports
--    数据来源：卖家中心 → 广告 → 衡量与报告（SP/SD/SB，CSV）
-- ============================================================
create table if not exists public.ad_reports (
  id bigint generated by default as identity primary key,
  date text,
  campaign_name text,
  campaign_id text,
  ad_group_name text,
  targeting_type text,
  targeting text,
  keyword text,
  match_type text,
  impressions integer,
  clicks integer,
  ctr numeric,
  spend numeric,
  seven_day_total_sales numeric,
  acos numeric,
  roas numeric,
  orders integer,
  units integer,
  currency text,
  report_type text,
  store_id text,
  month text,
  dedup_key text,
  created_at timestamptz default now(),
  constraint ad_reports_dedup_key_unique unique (dedup_key)
);
create index if not exists idx_ad_reports_date on public.ad_reports (date);
create index if not exists idx_ad_reports_campaign on public.ad_reports (campaign_id);

-- ============================================================
-- 4. 库存报告 inventory_records
--    数据来源：FBA 库存报告 / 滞留库存报告 / 库存赔偿报告（CSV）
--    report_type: inventory(库存) / stranded(滞留) / reimbursement(赔偿)
-- ============================================================
create table if not exists public.inventory_records (
  id bigint generated by default as identity primary key,
  date text,
  report_type text,
  sku text,
  asin text,
  fnsku text,
  product_name text,
  condition text,
  available integer,
  reserved integer,
  inbound integer,
  total_qty integer,
  stranded_qty integer,
  stranded_reason text,
  case_id text,
  order_id text,
  currency text,
  amount numeric,
  qty_reimbursed_cash integer,
  qty_reimbursed_inventory integer,
  reimbursement_type text,
  store_id text,
  month text,
  dedup_key text,
  created_at timestamptz default now(),
  constraint inventory_records_dedup_key_unique unique (dedup_key)
);
create index if not exists idx_inventory_records_sku on public.inventory_records (sku);
create index if not exists idx_inventory_records_type on public.inventory_records (report_type);
